on: [push, pull_request]

name: CLI test

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup CADR
        run: sudo apt-get install gpg && gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 3D9E81D3CA76CDCBE768C4B4DC6B4F8E60B8CF4C && gpg --export 3D9E81D3CA76CDCBE768C4B4DC6B4F8E60B8CF4C | sudo apt-key add - && echo 'deb https://deb.ln-ask.me/beta buster common local' | sudo tee /etc/apt/sources.list.d/cryptoanarchy.list > /dev/null && sudo apt-get update
      - name: Install bitcoind and bitcoin-cli
        run: sudo apt-get install bitcoin-regtest bitcoin-cli
      - name: Build CLI
        run: cargo build --manifest-path cli/Cargo.toml
      - name: Run the test
        run: ./test.sh --bitcoin-cli "sudo bitcoin-cli"
